# smart sleep management for newborns and infants {#optimize baby sleep}

#### Keywords

baby, infant, infant sleep, baby sleep, sleep management, parent-infant sleep

## WAAAH!

Parents are presented today with an ever-increasing number of baby monitors. However, baby monitors only let parents observe their newborn's sleep patterns; there aren’t any products today that can help parents intelligently understand and manage their newborn's sleep. The Possums Sleep Intervention (PSI) is a new approach to infant sleep problems that is grounded within contextual behavioral science, cued care, and the biology of sleep. The aim is to support the healthful biological regulation of sleep as well as to optimize the infant's sleep efficiency and resilience. (Whittingham&Douglas, 2014)

## KEEP IT TOGETHER! 

This product will implement the PSI framework and use a suite of technologies (e.g., wearable devices, computer vision, and audio processing) to collect and aggregate data into a cross-platform app and in turn use machine learning to make recommendations to parents aimed at:

1. Identifying obstacles to healthy regulation of infant sleep (e.g. disrupted circadian pacemaker - obtaining sunlight in the morning; feed problems - excessively frequent feeds and associated excessive night-waking in breast-fed babies)

2. Reinforcing that cued-care is a pattern of care characterized by intentionally and sensibly responding to their baby’s cues. On the other hand, responding to the baby’s cues in a manner that is not what baby intends, with the aim of extinguishing signaling, is not cued care. 

The full list of PSI targeted intervention actions can be found in Whittingham’s paper. While there are many that can be easily checked, there will be technical challenges to recognize baby cues correctly and determine the best response. Fortunately, with the power of machine learning (limited by how much training data is available) coupled with computer vision to analyze each baby’s physical cues, a good recommendation can often be approximated with high accuracy to be shared with the new parents. Parents will also have the option to tweak the model by relabeling captured cues to reduce the false positive rate.   

## ALL IS WELL!

PSI was developed from scientific literature. Rather than promoting one-way parents enforced and potentially harmful sleep intervention actions (e.g. ignore pre-cry or cry cues; decouple sleep from feeds and bodily contact; fit their infant’s sleeping patterns to the average; lists of tired cues without understanding of context), this app will fully implement the PSI and provide an intuitive graphical user interface to promote flexible, value-driven actions to increase positive reinforcement.
