# FraudZoom

#### Keywords

insurance, fraud detection, SIU, claims analytics, claimant fraud, machine learning

## inadequate rule-based approach

Today, property & causulty insurance carriers have an increasing demand to reduce claim costs (through loss avoidance) with anti-fraud initiatives across business lines (e.g., auto, property, liability, and worker's compensation). While smaller insurers mostly rely on claims adjusters to manually (but proactively) make referrals to special investigations unit (SIU) departments, larger insurers have turned to IT to develop rule-based systems that can assign fraud scores (i.e., add up all fired rules' weighted scores to see if they are over a threshold) to claims and generate leads for SIU. However, these systems often feel inadequate and can have an overly manual, imprecise, and expensive process to create/update the rules and their associative weights when fraud pattern changes. With the help from data scientists, there are in fact more automated and intelligent approaches to generate these leads to SIU more reliably without overtaxing claims adjusters or having huge IT budgets.   

## smarter approach with data science

When a large number of rules (usually in the thousands) are involved, it is next to impossible for a human to know what is the “correct” weight to use for each of the rules. Subjective manual adjustments made to “tweak” the overall score are usually biased and suboptimal. There are in fact a couple ways data science can improve on the rule-based approach: 

1. If the problem is linearly solvable, (i.e., plane exists to separate the fraudulent from non-fraudulent claims), an algorithm called “perceptron” can be used to optimize the rule weights automatically to maximize a choice of statistical measure (e.g., Recall, Precision, or F1)

2. Regularization can also be applied during optimization to ensure that impactful rules receive more weights and trivial/outdated rules can be easily found and corrected. 

3. In practice, fraud detection is likely a non-linear problem, machine learning models like the support vector machine, random forest, combined with deep learning and natural language processing can better explore interactions among the rules and analyzing text based claim notes to boost fraud detection. 

## intelligent fraud detection    

Anti-fraud is generally a challenging area for data scientists. Not only the predictions need to be accurate but also they have to be interpretable and/or actionable. While rules based systems can break down a fraud score to triggered rules, it can be difficult to explain intuitively what a non-linear model does. Nonetheless, machine learning (ML) models often gain a non-trivial boost in prediction performance, and proper reason codes and visulizaitons can be created to support a prediction. More importantly, instead of second-guessing the scores coming out of a rule based system, those energies can be rechanneled to focus on handling of fraudulent claims such as evidence preparation and have proper preventative/remedial actions taken. It also makes more sense to make the SIU referral process more adaptive and robust while taking some pressure off claim ajusters and/or any labor-intensive manual process to tweak the rule-based systems.  
